### ISSUE TITLE
Not compatible with Java 8 or higher

### ISSUE THREAD

**Issue by jkransen** [3-Round-Stones/callimachus#271]
Hi, it's 2.5 years since the last commit, and I am curious what the status of this project is. Is it feature complete or is it abandoned for better alternatives? I am trying to install it locally on a linux, following the steps from the youtube video, and I fail with this error:

java.util.concurrent.ExecutionException: java.lang.AssertionError: Rhino not available
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.callimachusproject.Setup.start(Setup.java:243)
	at org.callimachusproject.Setup.main(Setup.java:109)
Caused by: java.lang.AssertionError: Rhino not available
	at org.callimachusproject.script.EmbeddedScriptEngine.<clinit>(EmbeddedScriptEngine.java:71)
	at org.callimachusproject.script.ScriptAdviceFactory.createEmbededScriptEngine(ScriptAdviceFactory.java:46)
	at org.callimachusproject.script.ScriptAdviceFactory.createAdvice(ScriptAdviceFactory.java:39)

I am using Java 1.8.0_201

**Comment by catch-point** [comment]
Callimachus requires jdk1.7. it does not work with java8 and later. The project is idle while waiting further funding and resources.


James


On Jul 1, 2019 3:24 PM, Jeroen Kransen <notifications@github.com> wrote:

Hi, it's 2.5 years since the last commit, and I am curious what the status of this project is. Is it feature complete or is it abandoned for better alternatives? I am trying to install it locally on a linux, following the steps from the youtube video, and I fail with this error:

java.util.concurrent.ExecutionException: java.lang.AssertionError: Rhino not available
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.callimachusproject.Setup.start(Setup.java:243)
at org.callimachusproject.Setup.main(Setup.java:109)
Caused by: java.lang.AssertionError: Rhino not available
at org.callimachusproject.script.EmbeddedScriptEngine.(EmbeddedScriptEngine.java:71)
at org.callimachusproject.script.ScriptAdviceFactory.createEmbededScriptEngine(ScriptAdviceFactory.java:46)
at org.callimachusproject.script.ScriptAdviceFactory.createAdvice(ScriptAdviceFactory.java:39)

**Comment by jkransen** [comment]
Ok, I'll rename the issue, as it is an issue since Java 7 is EOL.
